# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [3]:
!pip3 install mdutils
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [7]:
print(np.__version__)
np.show_config()

1.20.1
blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
Z = np.zeros(10)

#### 4. How to find the memory size of any array (★☆☆)

In [10]:
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [12]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [13]:
Z=np.zeros(10)
Z[4]=1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [14]:
#Z=[i for i in range(10,50)]
Z = np.arange(10,50)

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [24]:
Z=np.arange(10)
Z1=Z[::-1]
print(Z1)
Z2=list(Z)
Z2.reverse()
print(Z2)

[9 8 7 6 5 4 3 2 1 0]
[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [27]:
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [52]:
Z=[[1,2,0],[0,4,0]]
print(type(Z))
nz = np.nonzero(Z)
print(nz)
print(np.transpose(nz))

Z2=np.array(Z)
print(type(Z2))
nz2= np.argwhere(Z2!=0)
print(nz2)

<class 'list'>
(array([0, 0, 1]), array([0, 1, 1]))
[[0 0]
 [0 1]
 [1 1]]
<class 'numpy.ndarray'>
[[0 0]
 [0 1]
 [1 1]]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [54]:
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [57]:
Z=np.random.random((3,3,3))

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [62]:
Z=np.random.random((10,10))
Zmax=np.max(Z)
Zmin=np.min(Z)
print(Zmax,Zmin)

0.9959508190411515 0.00023769882541713194


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [63]:
Z=np.random.random(30)
Zmean=Z.mean()
print(Zmean)

0.45528313225600914


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [64]:
Z=np.ones((10,10))
Z[1:-1,1:-1]=0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [65]:
Z=np.ones((5,5))
Z= np.pad(Z,pad_width=1,mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [78]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.inf < np.nan)
print(np.nan - np.nan)
print(np.inf - np.inf)
print(np.inf)
print(np.nan in set([np.nan]))

print(0.3 == 3 * 0.1)
print(3*0.1)
print(3*np.float32(0.1))
print(np.float32(3*0.1))

nan
False
False
False
nan
nan
inf
True
False
0.30000000000000004
0.30000000447034836
0.3


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [81]:
Z=np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [84]:
Z=np.zeros((8,8),dtype=int)
Z[1::2,::2]=1
Z[::2,1::2]=1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [85]:
print(np.unravel_index(99,(6,7,8)))

(1, 5, 3)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [86]:
Z=np.tile([[0,1],[1,0]],(4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [87]:
Z=np.random.random((5,5))
Zmean=Z.mean()
Zstd=Z.std()
Z=(Z-Zmean)/Zstd
print(Z)

[[-1.11974754 -0.75183333  1.20194468  1.44681344 -0.70993548]
 [-0.40883191 -0.74698746 -1.23742094  0.55879233 -1.35887348]
 [-0.47137867 -1.28538356  0.61556668  0.68916688 -1.19890396]
 [-0.34815711  1.4283998   0.05809216 -0.76847446  1.22929724]
 [ 1.21280139  1.38745886  1.2740939  -1.06579463  0.36929517]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [88]:
color=np.dtype([('r',np.ubyte),
                ('g',np.ubyte),
                ('b',np.ubyte),
                ('a',np.ubyte)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [91]:
Z=np.dot(np.ones((5,3)),np.ones((3,2)))
print(Z)

Z=np.ones((5,3)) @ np.ones((3,2))
print(Z)

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]
[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [93]:
Z=np.arange(11)
Z[(Z<8)&(Z>3)]*=-1
print(Z)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [94]:
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [108]:
Z=np.arange(6,dtype=int)
print(Z)
print(Z**Z)
print(2 << Z >> 2)
print(Z <- Z)
print(1j*Z)
print(Z/1/1)
print(Z<Z>Z)


[0 1 2 3 4 5]
[   1    1    4   27  256 3125]
[ 0  1  2  4  8 16]
[False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
[0. 1. 2. 3. 4. 5.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [110]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]
ipykernel_launcher:1: RuntimeWarning: invalid value encountered in true_divide
ipykernel_launcher:2: RuntimeWarning: divide by zero encountered in floor_divide


#### 29. How to round away from zero a float array ? (★☆☆)

In [113]:
Z= np.random.uniform(-10,+10,10)
print(Z)

#method 1
print(np.copysign(np.ceil(np.abs(Z)),Z))

# method 2: More readable but less efficient
print(np.where(Z>0, np.ceil(Z), np.floor(Z)))

np.info(np.where)

[ 0.53510692 -7.1564307   1.52156678 -2.97134666  1.32895778  7.79891679
  8.52826169  2.21818326 -5.87116807 -7.5315754 ]
[ 1. -8.  2. -3.  2.  8.  9.  3. -6. -8.]
[ 1. -8.  2. -3.  2.  8.  9.  3. -6. -8.]
 where()

where(condition, [x, y])

Return elements chosen from `x` or `y` depending on `condition`.

.. note::
    When only `condition` is provided, this function is a shorthand for
    ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
    preferred, as it behaves correctly for subclasses. The rest of this
    documentation covers only the case where all three arguments are
    provided.

Parameters
----------
condition : array_like, bool
    Where True, yield `x`, otherwise yield `y`.
x, y : array_like
    Values from which to choose. `x`, `y` and `condition` need to be
    broadcastable to some shape.

Returns
-------
out : ndarray
    An array with elements from `x` where `condition` is True, and elements
    from `y` elsewhere.

See Also
--------
choose
n

#### 30. How to find common values between two arrays? (★☆☆)

In [125]:
Z1=np.random.randint(0,10,10).reshape(2,5)
Z2=np.random.randint(0,10,10).reshape(2,5)
#np.info(np.intersect1d)
print(np.intersect1d(Z1,Z2,return_indices=False))
print(np.intersect1d(Z1,Z2,return_indices=True))

[2 4 5 8]
(array([2, 4, 5, 8]), array([8, 1, 4, 3]), array([1, 5, 6, 8]))


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [135]:
defaults = np.seterr(all='ignore')
Z=np.ones(1)/0

#Back to sanity
_ = np.seterr(**defaults)

# Equivalently with a context manager
with np.errstate(all='ignore'):
    np.arange(3)/0

In [136]:
np.info(np.seterr)

 seterr(all=None, divide=None, over=None, under=None, invalid=None)

Set how floating-point errors are handled.

Note that operations on integer scalar types (such as `int16`) are
handled like floating point, and are affected by these settings.

Parameters
----------
all : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Set treatment for all types of floating-point errors at once:

    - ignore: Take no action when the exception occurs.
    - warn: Print a `RuntimeWarning` (via the Python `warnings` module).
    - raise: Raise a `FloatingPointError`.
    - call: Call a function specified using the `seterrcall` function.
    - print: Print a warning directly to ``stdout``.
    - log: Record error in a Log object specified by `seterrcall`.

    The default is not to change the current behavior.
divide : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
    Treatment for division by zero.
over : {'ignore', 'warn', 'raise', 'call', 'print', 'log'}, optional
  

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [138]:
print(np.sqrt(-1) == np.emath.sqrt(-1))
print(np.sqrt(-1))
print(np.emath.sqrt(-1))

False
nan
1j


#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [139]:
yesterday=np.datetime64('today')-np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today')+ np.timedelta64(1)
print(yesterday)
print(today)
print(tomorrow)

2021-06-22
2021-06-23
2021-06-24


In [140]:
np.info(np.datetime64)

 datetime64()

A datetime stored as a 64-bit integer, counting from ``1970-01-01T00:00:00``.

>>> np.datetime64(10, 'Y')
numpy.datetime64('1980')
>>> np.datetime64(10, 'D')
numpy.datetime64('1970-01-11')

See :ref:`arrays.datetime` for more information.

:Character code: ``'M'``


Methods:

  all  --  Scalar method identical to the corresponding array attribute.
  any  --  Scalar method identical to the corresponding array attribute.
  argmax  --  Scalar method identical to the corresponding array attribute.
  argmin  --  Scalar method identical to the corresponding array attribute.
  argsort  --  Scalar method identical to the corresponding array attribute.
  astype  --  Scalar method identical to the corresponding array attribute.
  byteswap  --  Scalar method identical to the corresponding array attribute.
  choose  --  Scalar method identical to the corresponding array attribute.
  clip  --  Scalar method identical to the corresponding array attribute.
  compress  --  Scalar method

In [141]:
np.info(np.timedelta64)

 timedelta64()

A timedelta stored as a 64-bit integer.

See :ref:`arrays.datetime` for more information.

:Character code: ``'m'``


Methods:

  all  --  Scalar method identical to the corresponding array attribute.
  any  --  Scalar method identical to the corresponding array attribute.
  argmax  --  Scalar method identical to the corresponding array attribute.
  argmin  --  Scalar method identical to the corresponding array attribute.
  argsort  --  Scalar method identical to the corresponding array attribute.
  astype  --  Scalar method identical to the corresponding array attribute.
  byteswap  --  Scalar method identical to the corresponding array attribute.
  choose  --  Scalar method identical to the corresponding array attribute.
  clip  --  Scalar method identical to the corresponding array attribute.
  compress  --  Scalar method identical to the corresponding array attribute.
  conj  --  None
  conjugate  --  Scalar method identical to the corresponding array attribute.
  c

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [142]:
Z=np.arange('2016-07','2016-08',dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [143]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)
print(A)

[-1.5 -1.5 -1.5]


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [145]:
Z=np.random.uniform(0,10,6)
print(Z-Z%1)
print(Z//1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[0. 6. 7. 2. 5. 4.]
[0. 6. 7. 2. 5. 4.]
[0. 6. 7. 2. 5. 4.]
[0 6 7 2 5 4]
[0. 6. 7. 2. 5. 4.]


In [146]:
np.info(np.trunc)

trunc(x, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Return the truncated value of the input, element-wise.

The truncated value of the scalar `x` is the nearest integer `i` which
is closer to zero than `x` is. In short, the fractional part of the
signed number `x` is discarded.

Parameters
----------
x : array_like
    Input data.
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninit

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [150]:
Z=np.tile(np.arange(5),(5,1))
print(Z)

# method 2: (better)
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]
[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [151]:
np.info(np.fromiter)

fromiter(iterable, dtype, count=-1, *, like=None)

Create a new 1-dimensional array from an iterable object.

Parameters
----------
iterable : iterable object
    An iterable object providing data for the array.
dtype : data-type
    The data-type of the returned array.
count : int, optional
    The number of items to read from *iterable*.  The default is -1,
    which means all data is read.
like : array_like
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. note::
        The ``like`` keyword is an experimental feature pending on
        acceptance of :ref:`NEP 35 <NEP35>`.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    The output array.

Notes
-----
Specify `count` to improve performance. 

In [153]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float, count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [154]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [155]:
np.info(np.linspace)

 linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None,
          axis=0)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

.. versionchanged:: 1.20.0
    Values are rounded towards ``-inf`` instead of ``0`` when an
    integer ``dtype`` is specified. The old behavior can
    still be obtained with ``np.linspace(start, stop, num).astype(int)``

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [161]:
Z = np.random.random(10)
Z.sort()
print(Z)

[0.06981861 0.15766614 0.31609253 0.37845033 0.55692366 0.63027548
 0.65474642 0.91326856 0.93576796 0.94322648]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [163]:
Z = np.arange(10)
a = np.add.reduce(Z)
print(a)

45


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [168]:
A=np.random.randint(0,2,5)
B=np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
print(np.allclose(A,B))

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
print(np.array_equal(A,B))

True
True


#### 43. Make an array immutable (read-only) (★★☆)

In [169]:
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [171]:
Z = np.random.random((10,2))
X,Y = Z[:,0],Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T) # in the range ``[-pi, pi]`

[0.59314534 0.47971265 1.05085672 0.7383304  0.78479207 1.17521219
 0.4819698  0.90460732 1.17037757 1.17892214]
[0.43718374 0.85078147 0.60875167 1.49520187 1.17468131 0.80243408
 0.96668434 1.34047108 0.73465377 0.60103759]


In [172]:
np.info(np.arctan2)

arctan2(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Element-wise arc tangent of ``x1/x2`` choosing the quadrant correctly.

The quadrant (i.e., branch) is chosen so that ``arctan2(x1, x2)`` is
the signed angle in radians between the ray ending at the origin and
passing through the point (1,0), and the ray ending at the origin and
passing through the point (`x2`, `x1`).  (Note the role reversal: the
"`y`-coordinate" is the first function parameter, the "`x`-coordinate"
is the second.)  By IEEE convention, this function is defined for
`x2` = +/-0 and for either or both of `x1` and `x2` = +/-inf (see
Notes for specific values).

This function is not defined for complex-valued arguments; for the
so-called argument of complex values, use `angle`.

Parameters
----------
x1 : array_like, real-valued
    `y`-coordinates.
x2 : array_like, real-valued
    `x`-coordinates.
    If ``x1.shape != x2.shape``, they must be broadcast

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [173]:
Z=np.random.random(10)
Z[Z.argmax()]=0
print(Z)

[0.58176535 0.90590095 0.33408242 0.54540755 0.84558609 0.47204638
 0.6560933  0.         0.67177563 0.20137161]


#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

In [174]:
Z = np.zeros((5,5),[('x',float),('y',float)])
Z['x'],Z['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [175]:
np.info(np.subtract.outer)

outer(A, B, /, **kwargs)

Apply the ufunc `op` to all pairs (a, b) with a in `A` and b in `B`.

Let ``M = A.ndim``, ``N = B.ndim``. Then the result, `C`, of
``op.outer(A, B)`` is an array of dimension M + N such that:

.. math:: C[i_0, ..., i_{M-1}, j_0, ..., j_{N-1}] =
   op(A[i_0, ..., i_{M-1}], B[j_0, ..., j_{N-1}])

For `A` and `B` one-dimensional, this is equivalent to::

  r = empty(len(A),len(B))
  for i in range(len(A)):
      for j in range(len(B)):
          r[i,j] = op(A[i], B[j]) # op = ufunc in question

Parameters
----------
A : array_like
    First array
B : array_like
    Second array
kwargs : any
    Arguments to pass on to the ufunc. Typically `dtype` or `out`.

Returns
-------
r : ndarray
    Output array

See Also
--------
numpy.outer : A less powerful version of ``np.multiply.outer``
              that `ravel`\ s all inputs to 1D. This exists
              primarily for compatibility with old code.

tensordot : ``np.tensordot(a, b, axes=((), ()))`` and
            

In [179]:
X = np.arange(5)
Y = X+0.5
C = 1.0 / np.subtract.outer(X,Y)
print(C)
print(np.linalg.det(C))

[[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4       ]
 [ 0.4         0.66666667  2.         -2.         -0.66666667]
 [ 0.28571429  0.4         0.66666667  2.         -2.        ]]
-131.91659501325745


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [180]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)

In [181]:
np.set_printoptions(threshold=float('inf'))
Z= np.zeros((40,40))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [183]:
Z = np.arange(100)
v = np.random.uniform(0,100)
print(v) # a scalar
index = (np.abs(Z-v)).argmin()
print(Z[index])

49.35267613311238
49


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [184]:
Z = np.zeros(6,[('position',[('x',float,1),
                              ('y',float,1)])
                              ,
                 ('color',[('r',float,1),
                           ('g',float,1),
                           ('b',float,1)])
                           ])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
ipykernel_launcher:6: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [185]:
np.info(np.atleast_2d)

 atleast_2d(*arys)

View inputs as arrays with at least two dimensions.

Parameters
----------
arys1, arys2, ... : array_like
    One or more array-like sequences.  Non-array inputs are converted
    to arrays.  Arrays that already have two or more dimensions are
    preserved.

Returns
-------
res, res2, ... : ndarray
    An array, or list of arrays, each with ``a.ndim >= 2``.
    Copies are avoided where possible, and views with two or more
    dimensions are returned.

See Also
--------
atleast_1d, atleast_3d

Examples
--------
>>> np.atleast_2d(3.0)
array([[3.]])

>>> x = np.arange(3.0)
>>> np.atleast_2d(x)
array([[0., 1., 2.]])
>>> np.atleast_2d(x).base is x
True

>>> np.atleast_2d(1, [1, 2], [[1, 2]])
[array([[1]]), array([[1, 2]]), array([[1, 2]])]


In [188]:
Z = np.random.random((5,2))
X,Y = np.atleast_2d(Z[:,0],Z[:,1])
D = np.sqrt((X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.77853864 1.16320485 1.13090267 0.33409621]
 [0.77853864 0.         0.71417284 0.63123621 0.45515765]
 [1.16320485 0.71417284 0.         0.09474458 0.87463221]
 [1.13090267 0.63123621 0.09474458 0.         0.82874847]
 [0.33409621 0.45515765 0.87463221 0.82874847 0.        ]]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [189]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y= Z.view(np.int32)
Y[:]=Z
print(Y)

[73 39 23 19 26 15 20 57 34 79]


#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [193]:
from io import StringIO

# Fake file
s = StringIO('''1, 2, 3, 4, 5

                6,  ,  , 7, 8

                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]
ipykernel_launcher:10: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [194]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [196]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
print(X)
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]
 [-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
   0.33333333  0.55555556  0.77777778  1.        ]


#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [200]:
n=5
v=3
Z=np.zeros((n,n))
np.put(Z,np.random.choice(range(n*n),v,replace=False),1)
print(Z)

[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]


In [199]:
np.info(np.put)

 put(a, ind, v, mode='raise')

Replaces specified elements of an array with given values.

The indexing works on the flattened target array. `put` is roughly
equivalent to:

::

    a.flat[ind] = v

Parameters
----------
a : ndarray
    Target array.
ind : array_like
    Target indices, interpreted as integers.
v : array_like
    Values to place in `a` at target indices. If `v` is shorter than
    `ind` it will be repeated as necessary.
mode : {'raise', 'wrap', 'clip'}, optional
    Specifies how out-of-bounds indices will behave.

    * 'raise' -- raise an error (default)
    * 'wrap' -- wrap around
    * 'clip' -- clip to the range

    'clip' mode means that all indices that are too large are replaced
    by the index that addresses the last element along that axis. Note
    that this disables indexing with negative numbers. In 'raise' mode,
    if an exception occurs the target array may still be modified.

See Also
--------
putmask, place
put_along_axis : Put elements by matching 

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [203]:
X = np.random.rand(3, 3)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)

[[-0.14413451  0.08076658  0.06336793]
 [ 0.13237265 -0.06269107 -0.06968158]
 [ 0.15118017 -0.08752624 -0.06365393]]


#### 59. How to sort an array by the nth column? (★★☆)

In [210]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[:,1].argsort())
print(Z[Z[:,1].argsort()])
#print(Z.sort(axis=Z[:,1])

[[7 3 2]
 [7 2 1]
 [0 7 4]]
[1 0 2]
[[7 2 1]
 [7 3 2]
 [0 7 4]]


In [207]:
np.info(np.sort)

 sort(a, axis=-1, kind=None, order=None)

Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecified fields will still b

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [219]:
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[2 0 1 0 0 2 1 1 1 1]
 [1 1 1 2 1 1 2 2 2 0]
 [0 1 1 2 2 2 2 0 1 1]]
False


In [213]:
np.info(np.any)

 any(a, axis=None, out=None, keepdims=<no value>, *, where=<no value>)

Test whether any array element along a given axis evaluates to True.

Returns single boolean unless `axis` is not ``None``

Parameters
----------
a : array_like
    Input array or object that can be converted to an array.
axis : None or int or tuple of ints, optional
    Axis or axes along which a logical OR reduction is performed.
    The default (``axis=None``) is to perform a logical OR over all
    the dimensions of the input array. `axis` may be negative, in
    which case it counts from the last to the first axis.

    .. versionadded:: 1.7.0

    If this is a tuple of ints, a reduction is performed on multiple
    axes, instead of a single axis or all the axes as before.
out : ndarray, optional
    Alternate output array in which to place the result.  It must have
    the same shape as the expected output and its type is preserved
    (e.g., if it is of type float, then it will remain so, returning
    1.0 f

#### 61. Find the nearest value from a given value in an array (★★☆)

In [224]:
Z = np.random.uniform(0,1,10)
z = 0.5
print(np.abs(Z - z).argmin())
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

1
0.5068557181012017


In [223]:
np.info(np.ndarray.flat)

A 1-D iterator over the array.

This is a `numpy.flatiter` instance, which acts similarly to, but is not
a subclass of, Python's built-in iterator object.

See Also
--------
flatten : Return a copy of the array collapsed into one dimension.

flatiter

Examples
--------
>>> x = np.arange(1, 7).reshape(2, 3)
>>> x
array([[1, 2, 3],
       [4, 5, 6]])
>>> x.flat[3]
4
>>> x.T
array([[1, 4],
       [2, 5],
       [3, 6]])
>>> x.T.flat[3]
5
>>> type(x.flat)
<class 'numpy.flatiter'>

An assignment example:

>>> x.flat = 3; x
array([[3, 3, 3],
       [3, 3, 3]])
>>> x.flat[[1,4]] = 1; x
array([[3, 1, 3],
       [3, 1, 3]])


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [234]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: 
    z[...] = x + y
    #z = x + y
print(it.operands[0])
print(it.operands[1])
print(it.operands[2])

[[0]
 [1]
 [2]]
[[0 1 2]]
[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [254]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj

Z = NamedArray(np.arange(10), "range_10")
print(Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [258]:

Z = np.ones(10)
I = np.random.randint(0,len(Z),20)

# method 1:
Z += np.bincount(I, minlength=len(Z))
print(Z)

# method 2:
np.add.at(Z, I, 1)
print(Z)

[4. 3. 3. 4. 3. 1. 2. 3. 3. 4.]
[4. 3. 3. 4. 3. 1. 2. 3. 3. 4.]


In [257]:
np.info(np.bincount)

 bincount()

bincount(x, weights=None, minlength=0)

Count number of occurrences of each value in array of non-negative ints.

The number of bins (of size 1) is one larger than the largest value in
`x`. If `minlength` is specified, there will be at least this number
of bins in the output array (though it will be longer if necessary,
depending on the contents of `x`).
Each bin gives the number of occurrences of its index value in `x`.
If `weights` is specified the input array is weighted by it, i.e. if a
value ``n`` is found at position ``i``, ``out[n] += weight[i]`` instead
of ``out[n] += 1``.

Parameters
----------
x : array_like, 1 dimension, nonnegative ints
    Input array.
weights : array_like, optional
    Weights, array of the same shape as `x`.
minlength : int, optional
    A minimum number of bins for the output array.

    .. versionadded:: 1.6.0

Returns
-------
out : ndarray of ints
    The result of binning the input array.
    The length of `out` is equal to ``np.amax(x)+

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [259]:
X = [1,2,3,4,5,6] # weights
I = [1,3,9,3,4,1] # bins
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [267]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

# Faster version
w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)
# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])
# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [271]:
A = np.random.randint(0,10,(3,4,3,4))
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print(sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
print(A.shape[:-2])
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[66 54 63 68]
 [50 37 62 49]
 [52 47 46 69]]
(3, 4)
[[66 54 63 68]
 [50 37 62 49]
 [52 47 46 69]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [273]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.40578762 0.59844953 0.53219495 0.49587103 0.62898184 0.49547753
 0.6129585  0.58205579 0.41677446 0.50553014]


#### 69. How to get the diagonal of a dot product? (★★★)

In [277]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
Z1=np.diag(np.dot(A, B))
print(Z1)
# Fast version
Z2=np.sum(A * B.T, axis=1)
print(Z2)
# Faster version
Z3=np.einsum("ij,ji->i", A, B)
print(Z3)

[0.95844272 0.99617936 0.68570052 1.68588502 0.50751204]
[0.95844272 0.99617936 0.68570052 1.68588502 0.50751204]
[0.95844272 0.99617936 0.68570052 1.68588502 0.50751204]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [278]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [279]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [280]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [295]:
faces = np.random.randint(0,5,(10,3))
# creat line segments from vertices
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
# (16,8) and (8,16)are the same line segment
F = np.sort(F,axis=1) 

# method 1:
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

# method 2:
L = np.unique(F,axis=0)
print(L)

[(0, 1) (0, 2) (0, 3) (0, 4) (1, 1) (1, 2) (1, 3) (1, 4) (2, 3) (3, 3)
 (3, 4)]
[[0 1]
 [0 2]
 [0 3]
 [0 4]
 [1 1]
 [1 2]
 [1 3]
 [1 4]
 [2 3]
 [3 3]
 [3 4]]


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [296]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [297]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n # remove the first 2 cumsum
Z = np.arange(20)
print(moving_average(Z, n=3))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


In [298]:
np.info(np.cumsum)

 cumsum(a, axis=None, dtype=None, out=None)

Return the cumulative sum of the elements along a given axis.

Parameters
----------
a : array_like
    Input array.
axis : int, optional
    Axis along which the cumulative sum is computed. The default
    (None) is to compute the cumsum over the flattened array.
dtype : dtype, optional
    Type of the returned array and of the accumulator in which the
    elements are summed.  If `dtype` is not specified, it defaults
    to the dtype of `a`, unless `a` has an integer dtype with a
    precision less than that of the default platform integer.  In
    that case, the default platform integer is used.
out : ndarray, optional
    Alternative output array in which to place the result. It must
    have the same shape and buffer length as the expected output
    but the type will be cast if necessary. See :ref:`ufuncs-output-type` for
    more details.

Returns
-------
cumsum_along_axis : ndarray.
    A new array holding the result is returned unle

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [299]:
Z = np.arange(10)
a=[]
for i in range(len(Z)-2):
    a.append([Z[i],Z[i+1],Z[i+2]])
print(a)


[[0, 1, 2], [1, 2, 3], [2, 3, 4], [3, 4, 5], [4, 5, 6], [5, 6, 7], [6, 7, 8], [7, 8, 9]]


In [305]:
# Method 2:
from numpy.lib import stride_tricks

def rolling(a,window):
    shape = (a.size - window +1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a,shape=shape,strides=strides)
Z = rolling(np.arange(10),3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [306]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.53316051,  0.7031455 , -0.26974851,  0.72746573,  0.99338504,
        0.49109344,  0.32778954,  0.638215  ,  0.64981462,  0.26794875,
        0.3942642 ,  0.27877238,  0.54269855,  0.35102889,  0.55075458,
       -0.6972999 ,  0.27773611, -0.61890292,  0.82692091, -0.11883652,
       -0.50696974,  0.25833131, -0.24151825,  0.90469103,  0.11757071,
        0.04803979,  0.50600871, -0.31495812, -0.34988753, -0.24699214,
       -0.109475  , -0.73018262,  0.80557444, -0.81872023,  0.07754912,
       -0.24392696,  0.06705406,  0.67159639,  0.46912975, -0.40931683,
       -0.18234937, -0.87029395, -0.89633419,  0.72415893, -0.78024189,
        0.85394831,  0.45791975,  0.70007269, -0.03584714,  0.78787301,
        0.27113782,  0.57963315, -0.87215947, -0.55245184, -0.78292127,
        0.85812752, -0.02005622, -0.83488712, -0.50874708,  0.26896787,
       -0.79662731,  0.50644065,  0.20254174,  0.32963394,  0.6843835 ,
        0.09903936,  0.76433601,  0.20152028, -0.55152244,  0.73

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [319]:
def distance(p0,p1,p):
    t=p1-p0
    l=(t**2).sum(axis=1)
    u= ((p[...,0]-p0[:,0])*t[:,0] + (p[...,1]-p0[:,1]*t[:,1])) /l
    u=u.reshape(len(u),1)
    d=p0+u*t-p
    return np.sqrt((d**2).sum(axis=1))

p0=np.random.uniform(-10,10,(10,2))
p1=np.random.uniform(-10,10,(10,2))
p =np.random.uniform(-10,10,( 1,2))
print(distance(p0,p1,p))


[ 1.96134176  3.3511554   3.01054062  7.54760751  6.42615494  8.62222141
 15.34261863  6.78587757  1.590051    7.8534142 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [320]:
# based on distance function from previous question
def distance(p0,p1,p):
    t=p1-p0
    l=(t**2).sum(axis=1)
    u= ((p[...,0]-p0[:,0])*t[:,0] + (p[...,1]-p0[:,1]*t[:,1])) /l
    u=u.reshape(len(u),1)
    d=p0+u*t-p
    return np.sqrt((d**2).sum(axis=1))

P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 5.52789703 13.10196682  5.85208732  6.14750678  3.62800728  5.47129089
  13.12936349  4.79732291 10.09741196  4.99614881]
 [ 9.99976369 15.21105441  7.78067492 13.49859307  8.37481553  8.75001812
   2.85590221 12.76711146  5.22866903  5.74374836]
 [14.90449624  2.93080344  7.38990224  2.87008512  1.18791704  5.04952598
   1.10168175  2.61050871  3.91388572  4.20504008]
 [ 8.63556662  5.85933271  2.92455591  4.07595745  0.30362675  1.27963438
   3.35951262  3.39957791  0.34525795  3.48885115]
 [10.1326306   7.08676603  3.06642641  5.9208847   2.41507074  1.925946
   1.39630508  5.34366773  1.98937469  1.87526079]
 [ 3.64956783 11.96188828  4.52031671  5.879611    2.6333537   4.43055921
  11.27009592  4.57891307  8.24012929  4.31804377]
 [ 9.21086496  6.74106104 10.16560606  5.4465606   7.28942045  9.05433466
   9.36673217  5.74652983  6.42549895 11.33774923]
 [ 8.47767055  4.45798304  4.9095818   2.14685602  2.04184145  3.50770256
   5.13180875  1.54018711  2.14498683  5.88295489]
 [

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [334]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
#print(R_start,R_stop)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[3 4 1 9 8 9 8 5 5 7]
 [2 5 0 8 3 0 3 4 3 9]
 [3 7 1 7 2 9 2 6 6 1]
 [4 5 2 5 3 2 3 1 3 7]
 [2 4 1 4 4 6 1 9 7 0]
 [2 0 6 6 8 1 7 1 3 9]
 [9 6 7 4 6 7 4 3 0 3]
 [4 3 5 6 9 3 7 2 8 9]
 [5 7 6 5 1 5 2 3 1 7]
 [7 2 6 1 7 9 9 6 7 9]]
[[0 0 0 0 0]
 [0 3 4 1 9]
 [0 2 5 0 8]
 [0 3 7 1 7]
 [0 4 5 2 5]]
ipykernel_launcher:24: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


In [323]:
np.info(slice)

 slice()

slice(stop)
slice(start, stop[, step])

Create a slice object.  This is used for extended slicing (e.g. a[0:10:2]).


Methods:

  indices  --  S.indices(len) -> (start, stop, stride)


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [350]:
Z= np.arange(1,15,dtype=np.uint64)
R= stride_tricks.as_strided(Z,(11,4),(8,8))
print(R)

Z= np.arange(1,15,dtype=np.uint32)
R= stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [353]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

10


#### 83. How to find the most frequent value in an array?

In [380]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

0


In [381]:
import collections
a=collections.Counter(list(Z))
Zmax=a.most_common(1)[0]
print(Zmax[0])


0


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [382]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

[[[[1 3 2]
   [1 2 0]
   [3 4 1]]

  [[3 2 0]
   [2 0 4]
   [4 1 3]]

  [[2 0 3]
   [0 4 1]
   [1 3 4]]

  [[0 3 4]
   [4 1 4]
   [3 4 3]]

  [[3 4 2]
   [1 4 3]
   [4 3 1]]

  [[4 2 2]
   [4 3 0]
   [3 1 0]]

  [[2 2 0]
   [3 0 4]
   [1 0 2]]

  [[2 0 4]
   [0 4 4]
   [0 2 1]]]


 [[[1 2 0]
   [3 4 1]
   [4 2 0]]

  [[2 0 4]
   [4 1 3]
   [2 0 2]]

  [[0 4 1]
   [1 3 4]
   [0 2 4]]

  [[4 1 4]
   [3 4 3]
   [2 4 2]]

  [[1 4 3]
   [4 3 1]
   [4 2 4]]

  [[4 3 0]
   [3 1 0]
   [2 4 4]]

  [[3 0 4]
   [1 0 2]
   [4 4 1]]

  [[0 4 4]
   [0 2 1]
   [4 1 4]]]


 [[[3 4 1]
   [4 2 0]
   [0 3 0]]

  [[4 1 3]
   [2 0 2]
   [3 0 1]]

  [[1 3 4]
   [0 2 4]
   [0 1 0]]

  [[3 4 3]
   [2 4 2]
   [1 0 1]]

  [[4 3 1]
   [4 2 4]
   [0 1 2]]

  [[3 1 0]
   [2 4 4]
   [1 2 3]]

  [[1 0 2]
   [4 4 1]
   [2 3 0]]

  [[0 2 1]
   [4 1 4]
   [3 0 1]]]


 [[[4 2 0]
   [0 3 0]
   [4 4 2]]

  [[2 0 2]
   [3 0 1]
   [4 2 0]]

  [[0 2 4]
   [0 1 0]
   [2 0 4]]

  [[2 4 2]
   [1 0 1]
   [0 4 4]]

  [[4 2 4]
   

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

In [384]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        #super(Symetric, self).__setitem__((i,j), value)   # python 2.x
        #super(Symetric, self).__setitem__((j,i), value)   # python 2.x
        super().__setitem__((i,j), value)  # python 3.x
        super().__setitem__((j,i),value)
        
def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 2  7 11  5 13]
 [ 7  4  9  2  8]
 [11  9  2 42  8]
 [ 5  2 42  0 15]
 [13  8  8 15  5]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

In [385]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [386]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0), np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


In [387]:
np.info(np.add.reduceat)

reduceat(array, indices, axis=0, dtype=None, out=None)

Performs a (local) reduce with specified slices over a single axis.

For i in ``range(len(indices))``, `reduceat` computes
``ufunc.reduce(array[indices[i]:indices[i+1]])``, which becomes the i-th
generalized "row" parallel to `axis` in the final result (i.e., in a
2-D array, for example, if `axis = 0`, it becomes the i-th row, but if
`axis = 1`, it becomes the i-th column).  There are three exceptions to this:

* when ``i = len(indices) - 1`` (so for the last index),
  ``indices[i+1] = array.shape[axis]``.
* if ``indices[i] >= indices[i + 1]``, the i-th generalized "row" is
  simply ``array[indices[i]]``.
* if ``indices[i] >= len(array)`` or ``indices[i] < 0``, an error is raised.

The shape of the output depends on the size of `indices`, and may be
larger than `array` (this happens if ``len(indices) > array.shape[axis]``).

Parameters
----------
array : array_like
    The array to act on.
indices : array_like
    Paired indices, 

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [389]:
# Author: Nicolas Rougier
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 0 0 0 0 0 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 0 1 0 0 0 0 1 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
  0 0 0 1 0 1 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

#### 89. How to get the n largest values of an array (★★★)

In [390]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


In [391]:
np.info(np.argpartition)

 argpartition(a, kth, axis=-1, kind='introselect', order=None)

Perform an indirect partition along the given axis using the
algorithm specified by the `kind` keyword. It returns an array of
indices of the same shape as `a` that index data along the given
axis in partitioned order.

.. versionadded:: 1.8.0

Parameters
----------
a : array_like
    Array to sort.
kth : int or sequence of ints
    Element index to partition by. The k-th element will be in its
    final sorted position and all smaller elements will be moved
    before it and all larger elements behind it. The order all
    elements in the partitions is undefined. If provided with a
    sequence of k-th it will partition all of them into their sorted
    position at once.
axis : int or None, optional
    Axis along which to sort. The default is -1 (the last axis). If
    None, the flattened array is used.
kind : {'introselect'}, optional
    Selection algorithm. Default is 'introselect'
order : str or list of str, optional

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

In [393]:
# Author: Stefan Van der Walt

def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    print(ix)
    ix = ix.reshape(len(arrays), -1).T
    print(ix)
    
    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[[[0 0]
   [0 0]]

  [[1 1]
   [1 1]]

  [[2 2]
   [2 2]]]


 [[[0 0]
   [1 1]]

  [[0 0]
   [1 1]]

  [[0 0]
   [1 1]]]


 [[[0 1]
   [0 1]]

  [[0 1]
   [0 1]]

  [[0 1]
   [0 1]]]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]
 [1 1 0]
 [1 1 1]
 [2 0 0]
 [2 0 1]
 [2 1 0]
 [2 1 1]]
[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [398]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [399]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

2.14 s ± 8.41 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
387 ms ± 8.58 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
346 ms ± 6.28 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [5]:
# Author: Gabe Schwartz

A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
print(C)
print(C.any((3,1)))
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[[[[False False]
   [False  True]]

  [[ True False]
   [False False]]

  [[False False]
   [False  True]]]


 [[[False False]
   [False  True]]

  [[False False]
   [ True False]]

  [[False False]
   [False False]]]


 [[[False False]
   [False  True]]

  [[ True False]
   [False False]]

  [[False False]
   [ True False]]]


 [[[False  True]
   [False False]]

  [[False  True]
   [False False]]

  [[ True False]
   [False False]]]


 [[[False  True]
   [False False]]

  [[False  True]
   [False False]]

  [[False  True]
   [False False]]]


 [[[False  True]
   [False False]]

  [[False False]
   [False  True]]

  [[False False]
   [ True False]]]


 [[[False False]
   [ True False]]

  [[False False]
   [False False]]

  [[ True False]
   [False False]]]


 [[[False False]
   [False  True]]

  [[False  True]
   [False False]]

  [[False  True]
   [False False]]]]
[[ True  True]
 [False  True]
 [ True  True]
 [ True False]
 [ True False]
 [ True  True]
 [ True  True]
 [ True  True]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [ ]:
# Author: Robert Kern

Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [6]:
# Author: Warren Weckesser

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])

# Author: Daniel T. McDonald

I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [7]:
# Author: Jaime Fernández del Río

Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# Author: Andreas Kouzelis
# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [11]:
# Author: Alex Riley
# Make sure to read: http://ajcr.net/Basic-guide-to-einsum/

A = np.random.uniform(0,1,5)
B = np.random.uniform(0,1,5)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.78090203, 0.29126117, 0.91667138, 0.2899054 , 0.42105448],
       [0.20443379, 0.0762498 , 0.2399771 , 0.07589487, 0.11022863],
       [0.53387147, 0.19912361, 0.62669154, 0.19819672, 0.2878581 ],
       [0.12343243, 0.04603788, 0.14489266, 0.04582358, 0.06655352],
       [0.11321056, 0.04222532, 0.13289359, 0.04202877, 0.06104199]])

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [13]:
# Author: Bas Swinckels

phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

In [16]:
np.info(np.interp)

 interp(x, xp, fp, left=None, right=None, period=None)

One-dimensional linear interpolation.

Returns the one-dimensional piecewise linear interpolant to a function
with given discrete data points (`xp`, `fp`), evaluated at `x`.

Parameters
----------
x : array_like
    The x-coordinates at which to evaluate the interpolated values.

xp : 1-D sequence of floats
    The x-coordinates of the data points, must be increasing if argument
    `period` is not specified. Otherwise, `xp` is internally sorted after
    normalizing the periodic boundaries with ``xp = xp % period``.

fp : 1-D sequence of float or complex
    The y-coordinates of the data points, same length as `xp`.

left : optional float or complex corresponding to fp
    Value to return for `x < xp[0]`, default is `fp[0]`.

right : optional float or complex corresponding to fp
    Value to return for `x > xp[-1]`, default is `fp[-1]`.

period : None or float, optional
    A period for the x-coordinates. This parameter allows th

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [18]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
print(M)
M &= (X.sum(axis=-1) == n)
print(M)
print(X[M])

[ True  True False]
[False  True False]
[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [21]:
# Author: Jessica B. Hamrick

X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1) 
print(means.shape) #(1000,)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

(1000,)
[-0.01509186  0.33559579]
